### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by eduardo4jesus** [jordan-g/PyTorch-cuDNN-Convolution#3]
I just cloned this project. As I am trying to run it I noticed it did not compile.

```
Using /home/eduardoj/.cache/torch_extensions/py39_cu113 as PyTorch extensions root...
Emitting ninja build file /home/eduardoj/.cache/torch_extensions/py39_cu113/cudnn_convolution/build.ninja...
Building extension module cudnn_convolution...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] c++ -MMD -MF cudnn_convolution.o.d -DTORCH_EXTENSION_NAME=cudnn_convolution -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/eduardoj/miniconda3/lib/python3.9/site-packages/torch/include -isystem /home/eduardoj/miniconda3/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /home/eduardoj/miniconda3/lib/python3.9/site-packages/torch/include/TH -isystem /home/eduardoj/miniconda3/lib/python3.9/site-packages/torch/include/THC -isystem /home/eduardoj/miniconda3/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -c /home/eduardoj/Repo/PyTorch-cuDNN-Convolution/cudnn_convolution.cpp -o cudnn_convolution.o 
FAILED: cudnn_convolution.o 
c++ -MMD -MF cudnn_convolution.o.d -DTORCH_EXTENSION_NAME=cudnn_convolution -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/eduardoj/miniconda3/lib/python3.9/site-packages/torch/include -isystem /home/eduardoj/miniconda3/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /home/eduardoj/miniconda3/lib/python3.9/site-packages/torch/include/TH -isystem /home/eduardoj/miniconda3/lib/python3.9/site-packages/torch/include/THC -isystem /home/eduardoj/miniconda3/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -c /home/eduardoj/Repo/PyTorch-cuDNN-Convolution/cudnn_convolution.cpp -o cudnn_convolution.o 
/home/eduardoj/Repo/PyTorch-cuDNN-Convolution/cudnn_convolution.cpp: In function ‘at::Tensor convolution(const at::Tensor&, const at::Tensor&, const at::Tensor&, c10::ArrayRef<long int>, c10::ArrayRef<long int>, c10::ArrayRef<long int>, int64_t, bool, bool)’:
/home/eduardoj/Repo/PyTorch-cuDNN-Convolution/cudnn_convolution.cpp:37:9: error: could not convert ‘bias’ from ‘const at::Tensor’ to ‘c10::IntArrayRef’ {aka ‘c10::ArrayRef<long int>’}
   37 |         bias,
      |         ^~~~
      |         |
      |         const at::Tensor
/home/eduardoj/Repo/PyTorch-cuDNN-Convolution/cudnn_convolution.cpp: In function ‘at::Tensor convolution_backward_weight(const at::Tensor&, c10::ArrayRef<long int>, const at::Tensor&, c10::ArrayRef<long int>, c10::ArrayRef<long int>, c10::ArrayRef<long int>, int64_t, bool, bool, bool)’:
/home/eduardoj/Repo/PyTorch-cuDNN-Convolution/cudnn_convolution.cpp:58:16: error: ‘cudnn_convolution_backward_weight’ is not a member of ‘at’; did you mean ‘cudnn_convolution_add_relu’?
   58 |     return at::cudnn_convolution_backward_weight(
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                cudnn_convolution_add_relu
/home/eduardoj/Repo/PyTorch-cuDNN-Convolution/cudnn_convolution.cpp: In function ‘at::Tensor convolution_backward_input(c10::ArrayRef<long int>, const at::Tensor&, const at::Tensor&, c10::ArrayRef<long int>, c10::ArrayRef<long int>, c10::ArrayRef<long int>, int64_t, bool, bool, bool)’:
/home/eduardoj/Repo/PyTorch-cuDNN-Convolution/cudnn_convolution.cpp:83:16: error: ‘cudnn_convolution_backward_input’ is not a member of ‘at’; did you mean ‘cudnn_convolution_add_relu’?
   83 |     return at::cudnn_convolution_backward_input(
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                cudnn_convolution_add_relu
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/eduardoj/miniconda3/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1740, in _run_ninja_build
    subprocess.run(
  File "/home/eduardoj/miniconda3/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/eduardoj/Repo/PyTorch-cuDNN-Convolution/example.py", line 5, in <module>
    cudnn_convolution = load(name="cudnn_convolution", sources=["cudnn_convolution.cpp"], verbose=True)
  File "/home/eduardoj/miniconda3/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1144, in load
    return _jit_compile(
  File "/home/eduardoj/miniconda3/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1357, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/eduardoj/miniconda3/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1469, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/eduardoj/miniconda3/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1756, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'cudnn_convolution'
```

---

I am using
- Torch `'1.11.0'`
- CUDNN `8200`
- CUDA Version `11.7`

**Comment by fufeisi** [comment]
Get the same issue. I think it's because: https://discuss.pytorch.org/t/cuda-error-with-cudnn-convolution-backward-weight-function/41214/9. Any solution so far?
